name: mopol
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - pytorch
  - numpy
  - plotly
  - tqdm
  - rpy2
  - botorch
  - pip
  - r-tidyverse
  - r-rpart
  - r-policytree
  - pip:
      - ax-platform
